[theme]
base = "light"
primaryColor = "#00b894"
backgroundColor = "#f6f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#142033"
borderColor = "#e7eaf3"
showWidgetBorder = true
baseRadius = "1rem"
font = "'Open Sans':https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
baseFontSize = 14
baseFontWeight = 400
headingFont = "'Open Sans':https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
headingFontWeights = [800, 700, 700]
headingFontSizes = ["2.9rem", "2rem", "1.1rem"]

[client]
showSidebarNavigation = false
toolbarMode = "minimal"
